# packages in environment at /Users/CamillaTafuro/miniconda3:
#
# Name                    Version                   Build  Channel
brotlipy                  0.7.0           py310hca72f7f_1002  
bzip2                     1.0.8                h1de35cc_0  
ca-certificates           2023.01.10           hecd8cb5_0  
certifi                   2022.12.7       py310hecd8cb5_0  
cffi                      1.15.1          py310h6c40b1e_3  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
conda                     23.1.0          py310hecd8cb5_0  
conda-content-trust       0.1.3           py310hecd8cb5_0  
conda-package-handling    2.0.2           py310hecd8cb5_0  
conda-package-streaming   0.7.0           py310hecd8cb5_0  
cryptography              38.0.4          py310hf6deb26_0  
idna                      3.4             py310hecd8cb5_0  
libffi                    3.4.2                hecd8cb5_6  
ncurses                   6.4                  hcec6c5f_0  
openssl                   1.1.1s               hca72f7f_0  
pip                       22.3.1          py310hecd8cb5_0  
pluggy                    1.0.0           py310hecd8cb5_1  
pycosat                   0.6.4           py310hca72f7f_0  
pycparser                 2.21               pyhd3eb1b0_0  
pyopenssl                 22.0.0             pyhd3eb1b0_0  
pysocks                   1.7.1           py310hecd8cb5_0  
python                    3.10.9               h218abb5_0  
python.app                3               py310hca72f7f_0  
readline                  8.2                  hca72f7f_0  
requests                  2.28.1          py310hecd8cb5_0  
ruamel.yaml               0.17.21         py310hca72f7f_0  
ruamel.yaml.clib          0.2.6           py310hca72f7f_1  
setuptools                65.6.3          py310hecd8cb5_0  
six                       1.16.0             pyhd3eb1b0_1  
sqlite                    3.40.1               h880c91c_0  
tk                        8.6.12               h5d9f67b_0  
toolz                     0.12.0          py310hecd8cb5_0  
tqdm                      4.64.1          py310hecd8cb5_0  
tzdata                    2022g                h04d1e81_0  
urllib3                   1.26.14         py310hecd8cb5_0  
wheel                     0.37.1             pyhd3eb1b0_0  
xz                        5.2.10               h6c40b1e_1  
zlib                      1.2.13               h4dc903c_0  
zstandard                 0.18.0          py310hca72f7f_0  
